export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const FETCH_QUIZZES = 'FETCH_QUIZZES';
export const SET_QUIZZES = 'SET_QUIZZES';
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR';
export const SET_LOADING = 'SET_LOADING';

export const FETCH_QUIZ_HEADER = 'FETCH_QUIZ_HEADER';
export const SET_QUIZ_HEADER = 'SET_QUIZ_HEADER';
export const FETCH_QUIZ_HEADER_ERROR = 'FETCH_QUIZ_HEADER_ERROR';
// export const SET_LOADING = 'SET_LOADING';

export const FETCH_QUIZ_QUESTIONS = 'FETCH_QUIZ_QUESTIONS';
export const SET_QUIZ_QUESTIONS = 'SET_QUIZ_QUESTIONS';
export const FETCH_QUIZ_QUESTIONS_ERROR = 'FETCH_QUIZ_QUESTIONS_ERROR';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PICK_ANSWER = 'PICK_ANSWER';
export const SUBMIT_ANWERS = 'SUBMIT_ANSWERS';
export const MARK_INVALID = 'MARK_INVALID';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_RESULT = 'SET_RESULT';